
# A string used as a secret key for API requests from edge functions
project_id = "aywxtonoyuyhpkldkzhc"

[functions.send-absence-notification]
verify_jwt = false

[functions.send-bulk-notifications]
verify_jwt = false
