
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aywxtonoyuyhpkldkzhc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5d3h0b25veXV5aHBrbGRremhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwNjE3NDYsImV4cCI6MjA1NjYzNzc0Nn0.2TG8W042hYJXDg_RY0S0kjheB4gUD5IyOp-fcAQTjAE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Custom TypeScript type extension for the new table that isn't in the auto-generated types
type CustomDatabase = Database & {
  public: {
    Tables: {
      attendance_notifications: {
        Row: {
          id: string;
          student_id: string;
          notification_type: string;
          notification_date: string;
          message: string;
          success: boolean;
        };
        Insert: {
          id?: string;
          student_id: string;
          notification_type: string;
          notification_date?: string;
          message: string;
          success?: boolean;
        };
        Update: {
          id?: string;
          student_id?: string;
          notification_type?: string;
          notification_date?: string;
          message?: string;
          success?: boolean;
        };
      };
    } & Database['public']['Tables'];
  } & Database['public'];
};

export const supabase = createClient<CustomDatabase>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
